apiVersion: v1
kind: Service
metadata:
  name: prometheus-kafka-exporter
  namespace: prometheus-kafka-exporter
  labels:
    app: prometheus-kafka-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: prometheus-kafka-exporter
